### ISSUE TITLE
Weird display 

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#10]
So I integrated, following your example with my engine, I get no errors, but my display is this for the exampleUI window
![Screenshot from 2020-06-18 17-52-45](https://user-images.githubusercontent.com/37628526/85076222-b72e6e80-b18d-11ea-9ac0-efd88a011971.png)

Any help will be appreciated.

**Comment by SpaiR** [comment]
I can't give any advice on that without context of what are you doing. What do you mean by "your engine"? I see you're using Vulkan API. The only available renderer for now is for OpenGL. So to use dear imgui with VK you need to write your own renderer for it.

**Comment by gviznyuk** [comment]
`

    @Override
    public void update(Void info) {

        do {

            ImGui.newFrame();
            beginRecord();
            ImGui.render();

        } while (ImGui.getDrawData().getCmdListsCount() == 0);

        renderGui(ImGui.getDrawData(), this.memoryProperties);
        record(renderList);

        for (String key : renderList.getKeySet()) {
            if (!renderCommandBuffers.containsKey(key)) {
                VkRenderInfo mainRenderInfo = (VkRenderInfo) renderList.get(key)
                        .getComponent(VkNodeComponentType.MAIN_RENDERINFO);
                renderCommandBuffers.put(key, mainRenderInfo.getCommandBuffer());
            }
        }
        if (!renderList.getObjectList().isEmpty()) {
            primaryCmdBuffer.reset();
            primaryCmdBuffer.record(getParameters().getDefaultFrameBuffer().getRenderPass().getId(),
                    getParameters().getDefaultFrameBuffer().getFrameBuffer().getHandle(),
                    getParameters().getDefaultFrameBuffer().getWidth(),
                    getParameters().getDefaultFrameBuffer().getHeight(),
                    getParameters().getDefaultFrameBuffer().getColorAttachmentCount(),
                    getParameters().getDefaultFrameBuffer().getDepthAttachmentCount(),
                    ValidationUtil.createPointerBuffer(renderCommandBuffers.values()));
            submitInfo.submit(getParameters().getQueue());
        }
        super.update();
    }

private void renderGui(ImDrawData drawData, VkPhysicalDeviceMemoryProperties memoryProperties) {

        ImVec2 size = new ImVec2();
        ImVec2 frameBuffer = new ImVec2();
        drawData.getDisplaySize(size);
        drawData.getFramebufferScale(frameBuffer);
        // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
        int fb_width = (int) (size.x * frameBuffer.x);
        int fb_height = (int) (size.y * frameBuffer.y);
        if (fb_width <= 0 || fb_height <= 0)
            return;

        if (drawData.getTotalVtxCount() > 0) {

            final int sizeImDrawVert = SIZEOF_IM_DRAW_VERT;
            final int sizeImDrawIdx = SIZEOF_IM_DRAW_IDX;
            // Create or resize the vertex/index buffers
            int vertexSize = drawData.getTotalVtxCount() * sizeImDrawVert;
            int indexSize = drawData.getTotalIdxCount() * sizeImDrawIdx;

            if (vertexBuffer == null || vertexBuffer.getAllocationSize() < vertexSize) {
                vertexBuffer = createOrResizeBuffer(vertexBuffer, vertexBuffer == null ? VK_NULL_HANDLE : vertexBuffer.getMemory(),  vertexSize, VK_BUFFER_USAGE_VERTEX_BUFFER_BIT);
            }
            if (indexBuffer == null || indexBuffer.getAllocationSize() < indexSize) {
                indexBuffer = createOrResizeBuffer(indexBuffer, indexBuffer == null ? VK_NULL_HANDLE : indexBuffer.getMemory(),  vertexSize, VK_BUFFER_USAGE_INDEX_BUFFER_BIT);
            }

            PointerBuffer pData = memAllocPointer(1);
            int err = vkMapMemory(device.getHandle(), vertexBuffer.getMemory(), 0, vertexSize, 0, pData);
            long vtxDst = pData.get(0);
            memFree(pData);
            if (err != VK_SUCCESS) {
                throw new AssertionError("Failed to map buffer memory: " + ValidationUtil.translateVulkanResult(err));
            }

            PointerBuffer pData2 = memAllocPointer(1);
            err = vkMapMemory(device.getHandle(), indexBuffer.getMemory(), 0, indexSize, 0, pData2);
            long idxDst = pData2.get(0);
            memFree(pData2);
            if (err != VK_SUCCESS) {
                throw new AssertionError("Failed to map buffer memory: " + ValidationUtil.translateVulkanResult(err));
            }
            for (int n = 0; n < drawData.getCmdListsCount(); n++) {

                memCopy(memAddress(drawData.getCmdListVtxBufferData(n)), vtxDst, drawData.getCmdListVtxBufferSize(n) * sizeImDrawVert);
                memCopy(memAddress(drawData.getCmdListIdxBufferData(n)), idxDst, drawData.getCmdListIdxBufferSize(n) * sizeImDrawIdx);
                vtxDst += drawData.getCmdListVtxBufferSize(n);
                idxDst += drawData.getCmdListIdxBufferSize(n);
            }
            VkMappedMemoryRange.Buffer range = VkMappedMemoryRange.calloc(2);
            range.get(0)
                    .sType(VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE)
                    .pNext(0)
                    .memory(vertexBuffer.getMemory())
                    .size(VK_WHOLE_SIZE);
            range.get(1)
                    .sType(VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE)
                    .pNext(0)
                    .memory(indexBuffer.getMemory())
                    .size(VK_WHOLE_SIZE);

            err = vkFlushMappedMemoryRanges(device.getHandle(), range);
            if (err != VK_SUCCESS) {
                throw new AssertionError("Failed to map buffer memory: " + ValidationUtil.translateVulkanResult(err));
            }
            vkUnmapMemory(device.getHandle(), vertexBuffer.getMemory());
            vkUnmapMemory(device.getHandle(), indexBuffer.getMemory());

            setupRenderState(drawData, drawData.getTotalIdxCount(), fb_width, fb_height);
        }
    }

    private void setupRenderState(ImDrawData drawData, int indexCount, int fbWidth, int fbHeight) {
        ImVec2 size = new ImVec2();
        ImVec2 pos = new ImVec2();
        drawData.getDisplaySize(size);
        drawData.getDisplayPos(pos);

        final float left = pos.x;
        final float right = pos.x + size.x;
        final float top = pos.y;
        final float bottom = pos.y + size.y;

        projectionMatrix.mapMemory(VkBufferUtil.createByteBuffer(new Matrix4f().OrthographicProjection2(left, right, bottom, top)));

        this.secondaryCmdBuffer.beginRecordSecondary(VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT,
                getParameters().getDefaultFrameBuffer().getFrameBuffer().getHandle(),
                getParameters().getDefaultFrameBuffer().getRenderPass().getId(),
                0);
        this.secondaryCmdBuffer.bindGraphicsPipelineCmd(this.pipeline.getHandle());
        this.secondaryCmdBuffer.bindGraphicsDescriptorSetsCmd(pipeline.getLayoutHandle(), ValidationUtil.createLongArray(descriptorSets));

        if(SIZEOF_IM_DRAW_IDX != 2) {
            this.secondaryCmdBuffer.bindVertexInputCmd(vertexBuffer.getId(), indexBuffer.getId());
        } else this.secondaryCmdBuffer.bindVertexInputCmd16(vertexBuffer.getId(), indexBuffer.getId());
        this.secondaryCmdBuffer.viewPortCmd(fbWidth, fbHeight);
        // Will project scissor/clipping rectangles into framebuffer space
        ImVec2 clipOff = new ImVec2();
        drawData.getDisplayPos(clipOff);         // (0,0) unless using multi-viewports
        ImVec2 clipScale = new ImVec2();
        drawData.getFramebufferScale(clipScale); // (1,1) unless using retina display which are often (2,2)

        // Render command lists
        // (Because we merged all buffers into a single one, we maintain our own offset into them)
        int globalVtxOffset = 0;
        int globalIdxOffset = 0;

        for (int n = 0; n < drawData.getCmdListsCount(); n++) {
            for (int cmd_i = 0; cmd_i < drawData.getCmdListCmdBufferSize(n); cmd_i++) {
                ImVec4 clipRect = new ImVec4();
                drawData.getCmdListCmdBufferClipRect(n, cmd_i, clipRect);

                float clipRectX = (clipRect.x - clipOff.x) * clipScale.x;
                float clipRectY = (clipRect.y - clipOff.y) * clipScale.y;
                float clipRectZ = (clipRect.z - clipOff.x) * clipScale.x;
                float clipRectW = (clipRect.w - clipOff.y) * clipScale.y;
                if (clipRectX < (float)fbWidth && clipRectY < (float)fbHeight && clipRectZ >= 0.0F && clipRectW >= 0.0F) {
                    // Negative offsets are illegal for vkCmdSetScissor
                    if (clipRectX < 0.0f)
                        clipRectX = 0.0f;
                    if (clipRectY < 0.0f)
                        clipRectY = 0.0f;

                    // Apply scissor/clipping rectangle
                    VkRect2D.Buffer scissor = VkRect2D.calloc(1);

                    VkOffset2D.Buffer offset = VkOffset2D.calloc(1);
                        offset.x((int)clipRectX);
                        offset.y((int)clipRectY);
                    scissor.offset(offset.get());
                    VkExtent2D.Buffer vkExtent = VkExtent2D.calloc(1);
                    vkExtent.width((int)(clipRectZ - clipRectX));
                    vkExtent.height((int)(clipRectW - clipRectY));
                    scissor.extent(vkExtent.get());

                    vkCmdSetScissor(this.secondaryCmdBuffer.getHandle(), 0,  scissor);

                    int elemCount = drawData.getCmdListCmdBufferElemCount(n, cmd_i);
                    int idxBufferOffset = drawData.getCmdListCmdBufferIdxOffset(n, cmd_i);
                    int vtxBufferOffset = drawData.getCmdListCmdBufferVtxOffset(n, cmd_i);
                    // Draw
                    vkCmdDrawIndexed(this.secondaryCmdBuffer.getHandle(), elemCount, 1,
                            idxBufferOffset + globalIdxOffset, vtxBufferOffset + globalVtxOffset, 0);
                }
            }
            globalIdxOffset += drawData.getCmdListIdxBufferSize(n);
            globalVtxOffset += drawData.getCmdListVtxBufferSize(n);
        }
        this.secondaryCmdBuffer.finishRecord();
    }

    private VkBuffer createOrResizeBuffer(VkBuffer vertexBuffer, long memory,  int vertexSize, int usage) {

        if (vertexBuffer != null)
            vkDestroyBuffer(device.getHandle(), vertexBuffer.getId(), null);
        if (memory != VK_NULL_HANDLE)
            vkFreeMemory(device.getHandle(), memory, null);

        int vertexBufferSizeAligned = ((vertexSize - 1) / 256 + 1) * 256;

        VkBuffer buffer = new VkBuffer(device.getHandle(), vertexBufferSizeAligned, usage);
        buffer.allocate(memoryProperties, VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT);
        buffer.bindBufferMemory();
        return buffer;
    }`

**Comment by gviznyuk** [comment]
Greetings,

Sorry, I accidentally closed the issue in your github repository.

Thanks,
Georgii

**Comment by SpaiR** [comment]
I see. I'm not familiar with Vulkan API, so I can only recommend you to pay more attention to the original code https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_vulkan.cpp My guess is that you're missing something important here. At least from the experience of porting opengl renderer, I've had problems after unintentional missing of some line of code. Right now opengl renderer is a 1 to 1 copy of the original. I would recommend you to do the same for vulkan.

Also, if you'll manage how to do things properly, I will be glad to add vulkan renderer to the binding repository. Thus contributions are welcom.
