### ISSUE TITLE
Embedded Window (ImGui.Begin())

### ISSUE THREAD

**Issue by blockout22** [SpaiR/imgui-java#104]
This might not be an issue for you (unless you do make changes) but when you embed 2 windows together with docking enable and you dock the **Inner** window ( `begin("new") `) in the **Center** of the **Outer** window ( `begin("New Window")` ) the windows begin to flicker and a restart is required to fix it ... no other docking location cause this issue 

EDIT: This bug also occurs when docking the other way but only when you select the inner window Tab 

![image](https://user-images.githubusercontent.com/4086993/147861815-04ba7a55-3b03-41ef-9658-65c1dec56f34.png)

**Comment by SpaiR** [comment]
Looks like an issue of Dear ImGui itself. Please create a report there: [Dear ImGui](https://github.com/ocornut/imgui).
Binding uses the library, by doing direct calls to native methods. There is nothing to be fixed from the binding side.
