### ISSUE TITLE
ImFontGlyphRangesBuilder.addRanges should be char

### ISSUE THREAD

**Issue by immetoo** [SpaiR/imgui-java#108]
When adding chinese and tone letters it overflows the short type and should be char instead;
```
    public static final short[] glyphRangesToneLetters0 = new short[]{0x02E5, 0x02E9, 0};
    public static final char[] glyphRangesToneLetters1 = new char[]{0xA708, 0xA716};
```

When adding the range via addText as an workaround it works;
```
        rangesBuilder.addText("@Ω仙⁴ ˧꜏⋇꜊꜔ ⁴ﷲΩ@");
        rangesBuilder.addText("©Δ∞ 仙上主天");
```
![imgui-java-unicode](https://user-images.githubusercontent.com/18482607/150327175-7ccd7941-10e9-4eee-94f7-f25aeb6c28da.png)

It almost renders correct, see the text version;
     @Ω仙⁴ ˧꜏⋇꜊꜔ ⁴ﷲΩ@    
        ©Δ∞ 仙上主天       
בְּרֵאשִׁית :o: יְסוֺד :o: יִשְׂרָאֵל
Welcome to the matrix.
encoder1=EW₁T5D⁴
91=˩˥˧˧˩˥

**Comment by immetoo** [comment]
This is duplicate #70
Have replace all my ranges code,with a call to the following workaround code;
```
	private static void addRangeUnicodePlane0(ImFontGlyphRangesBuilder fontBuilder) {
		for (int c=0x0100;c<=0xFFEF;c++) {
			StringBuilder buf = new StringBuilder();
			buf.append(""+(char)c);
			fontBuilder.addText(buf.toString());
		}
	}
```

**Comment by SpaiR** [comment]
duplicated #70
