### ISSUE TITLE
Bindings for Memory Editor

### ISSUE THREAD

**Issue by FlorianMichael** [SpaiR/imgui-java#109]
Would be nice to have bindings for https://github.com/ocornut/imgui_club

**Comment by tlf30** [comment]
Oh that is a cool binding. 
I am currently working on dynamic vulkan descriptor sets for an in-house rendering engine over the next couple days, but if I get time over the next week I might tackle this one. If someone else would like to do it, I would be more than happy to answer any questions.  I will be flying back to work on Feb. 1, and will be there for three weeks this time, so if I do not get to it before then it may be a while before I can.

**Comment by FlorianMichael** [comment]
thank you
