### ISSUE TITLE
UserCallback bindings

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#11]
How are you handling situations when the render state changes, in vulkan they are using a callback function. Is it possible for you to quickly add this binding to your native library?

```
`    // Render command lists
    // (Because we merged all buffers into a single one, we maintain our own offset into them)
    int global_vtx_offset = 0;
    int global_idx_offset = 0;
    for (int n = 0; n < draw_data->CmdListsCount; n++)
    {
        const ImDrawList* cmd_list = draw_data->CmdLists[n];
        for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.Size; cmd_i++)
        {
            const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
            if (pcmd->UserCallback != NULL)
            {
                // User callback, registered via ImDrawList::AddCallback()
                // (ImDrawCallback_ResetRenderState is a special callback value used by the user to request the renderer to reset render state.)
                if (pcmd->UserCallback == ImDrawCallback_ResetRenderState)
                    ImGui_ImplVulkan_SetupRenderState(draw_data, command_buffer, rb, fb_width, fb_height);
                else
                    pcmd->UserCallback(cmd_list, pcmd);
            }
            else
            {
                // Project scissor/clipping rectangles into framebuffer space
                ImVec4 clip_rect;
                clip_rect.x = (pcmd->ClipRect.x - clip_off.x) * clip_scale.x;
                clip_rect.y = (pcmd->ClipRect.y - clip_off.y) * clip_scale.y;
                clip_rect.z = (pcmd->ClipRect.z - clip_off.x) * clip_scale.x;
                clip_rect.w = (pcmd->ClipRect.w - clip_off.y) * clip_scale.y;

                if (clip_rect.x < fb_width && clip_rect.y < fb_height && clip_rect.z >= 0.0f && clip_rect.w >= 0.0f)
                {
                    // Negative offsets are illegal for vkCmdSetScissor
                    if (clip_rect.x < 0.0f)
                        clip_rect.x = 0.0f;
                    if (clip_rect.y < 0.0f)
                        clip_rect.y = 0.0f;

                    // Apply scissor/clipping rectangle
                    VkRect2D scissor;
                    scissor.offset.x = (int32_t)(clip_rect.x);
                    scissor.offset.y = (int32_t)(clip_rect.y);
                    scissor.extent.width = (uint32_t)(clip_rect.z - clip_rect.x);
                    scissor.extent.height = (uint32_t)(clip_rect.w - clip_rect.y);
                    vkCmdSetScissor(command_buffer, 0, 1, &scissor);

                    // Draw
                    vkCmdDrawIndexed(command_buffer, pcmd->ElemCount, 1, pcmd->IdxOffset + global_idx_offset, pcmd->VtxOffset + global_vtx_offset, 0);
                }
            }
        }
        global_idx_offset += cmd_list->IdxBuffer.Size;
        global_vtx_offset += cmd_list->VtxBuffer.Size;
    }`
```

**Comment by SpaiR** [comment]
UserCallback is an optional feature for a very custom routine. C++ version of the OpenGL renderer has it too. Yet the Java version doesn't utilize it and works fine. I believe VK has the same situation. Otherwise, please, provide more context about things you propose. Clearer reasons to implement, how it could be tested to ensure that it works fine etc.

**Comment by calvertdw** [comment]
I think the addCallback method on the ImDrawList would be a good addition to this library. For instance, I have a 3D scene that I want to move around in a window. Without the callback, I have to render the scene at some time without respect to ImGui's drawing of windows. Without it, you can only choose to render the scene behind or infront of all windows.

**Comment by gviznyuk** [comment]
Greetings,

sounds good!

Thanks,
Georgii

**Comment by SpaiR** [comment]
> For instance, I have a 3D scene that I want to move around in a window.
> Without it, you can only choose to render the scene behind or infront of all windows.

@calvertdw You need to use framebuffers for that. Basically, you bind a framebuffer, bind a texture to it and draw your scene there. Then you can use the texture anywhere you need to (`ImGui#image`, `ImDrawList#addImage` etc.). It's a common or even the only right approach you should use to draw something custom inside of Dear ImGui (in context of OpenGL). There are a lot of examples as well. (For C++, but they are translated to Java almost 1-to-1.)

**Comment by calvertdw** [comment]
Okay, sounds good. I wonder how much performance penalty that is, if any.

**Comment by calvertdw** [comment]
I got rendering to the ImGui window working via a framebuffer texture.

**Comment by gviznyuk** [comment]
Awesome, thanks!
Greetings,


Thanks,
Georgii
