### ISSUE TITLE
ImGui::TableGetSortSpecs() missing

### ISSUE THREAD

**Issue by Lenni0451** [SpaiR/imgui-java#114]
There is no binding for ImGui::TableGetSortSpecs().
https://github.com/ocornut/imgui/blob/master/imgui_demo.cpp#L5081

**Comment by phraktle** [comment]
I would be interested in seeing this exposed. Is there a workaround to get which column the table is sorted on?

**Comment by Lenni0451** [comment]
I don't think there is a workaround at the moment

**Comment by phraktle** [comment]
You can work out which column is sorted from the column flags, alas the direction is not exposed.

**Comment by assada** [comment]
Zero chance to implement table sorting wihout TableGetSortSpecs

**Comment by ultraq** [comment]
In case anybody else might find it useful, I implemented `ImGui.tableGetSortSpecs()` for the single sorting column use case on my own fork of imgui-java in this commit which people can copy: https://github.com/ultraq/imgui-java/commit/00fd84f2e7cf6b00e7895cb45f84ac16d0078b95

I expect that whenever the new API generation in #132 happens, which will probably also solve the multi-column sorting use case, then this will be out of date.
