### ISSUE TITLE
Bug: Unable to add multiple native libs

### ISSUE THREAD

**Issue by tmvkrpxl0** [SpaiR/imgui-java#118]
### Version

1.86.3

### What happened?

Process crashed, because it wasn't able to find libraries
It should not crash and display ImGui normally

### Reproduction

Add libraries for both linux and macos, and it becomes unable to load library
..I should note that I'm using it on Minecraft 1.18.1, which uses OpenGL 3.2.2

### Relevant log output

The log is clustered with non-imgui stuffs and locale is set to korean
the crash happens when it runs line `ImGui.createContext()`, which is `ImGuiDebugScreen.kt:22`
I'm using kotlin
Log: https://pastebin.com/LrG8CWWA
The actual exception starts with `java.lang.UnsatisfiedLinkError`, around line 716

**Comment by tmvkrpxl0** [comment]
Just simply adding native library for other OS causes this error

**Comment by SpaiR** [comment]
How do you add native libraries?

**Comment by tmvkrpxl0** [comment]
> How do you add native libraries?

Just adding them on build.gradle

**Comment by SpaiR** [comment]
And how do you add them to gradle? Can you provide code snippet? I'm asking, because from your description it seems that the problem is somewhere in that area.

**Comment by tmvkrpxl0** [comment]
https://www.toptal.com/developers/hastebin/osawapaniv.kotlin

This is `build.gradle.kts`, I hope you're familiar with this syntax
I'm using `library` instead of `implementation` as Minecraft forge has trouble adding external libraries. The `library` configuration is defined by me, and `implementation` extends from it

Also I'm doing very hacky stuff to prevent `imgui-java` from forcefully switching minecraft opengl version from 3.2.2 to anything else, by removing it both from dependencies and from class path.
The `minecraft.run.all{lazyToken(...)}` line at around line 127 is where I manually modify class path

Sorry, it may be a mess as it requires many additional dependencies and configurations

**Comment by SpaiR** [comment]
Can you try to add natives with `.dll`/`.so` files? Instruction can be found in README under the `Raw Jars` spoiler. To ensure, that the problem is no connected with adding of binaries.

**Comment by tmvkrpxl0** [comment]
@SpaiR I have tried manually loading .dll/.so files and It worked

**Comment by SpaiR** [comment]
Then it seems that the problem connected with the way you add libraries to gradle. 
```
library("io.github.spair:imgui-java-natives-linux:$imguiVersion")
```
Try specifically for natives to use `implementation` instead.

**Comment by tmvkrpxl0** [comment]
I have tried using `implementation` instead of `library` but it didn't worked. Even when there's only native lib defined in build.gradle.kts, it still crashes if I use `implementation` instead of `library`

**Comment by SpaiR** [comment]
I see. Then it seems that the problem with the classpath. Not sure I can give you any advice on this topic... This is how binding extracts native libs https://github.com/SpaiR/imgui-java/blob/main/imgui-binding/src/main/java/imgui/ImGui.java#L111-L128 . You can experiment with this code. I believe the problem is connected with minecraft environment.

**Comment by tmvkrpxl0** [comment]
It seems like linux native libs are not loaded into class path when window native lib is already present
`ImGui.class.getClassLoader().findResources("io/imgui")` returns only windows one

**Comment by tmvkrpxl0** [comment]
Hmm, I think `ModuleClassLoader` of Minecraft Forge 1.18 does not load 2 modules with same `Automatic-Module-Name` in META-INF file

**Comment by tmvkrpxl0** [comment]
I've just had a conversation with them and they seem to think that 2 modules having same `Automatic-Module-Name` is invalid. I could send PR to make it use different ones if you want
