### ISSUE TITLE
[Bug] Can't seem to add custom fonts. (ImGui window becomes black)

### ISSUE THREAD

**Issue by kingdevnl** [SpaiR/imgui-java#119]
[Bug] Can't seem to add custom fonts.

After calling io.getFonts().build(); the entire rendering of imgui seems to break (The entire window becomes dark)

[https://i.imgur.com/5NLiFVj.png](https://i.imgur.com/5NLiFVj.png)

```java
 static ImFont font;
    private void initFonts(final ImGuiIO io) {
        io.getFonts().addFontDefault();
        font = io.getFonts().addFontFromFileTTF("FuraCode.ttf", 14);
        io.getFonts().build();
    }
```
```java
    private void initImgui() {
        createContext();
        imGuiGlfw.init(getHandle(), true);
        imGuiGl3.init("#version 130");
        styleColorsDark();

        ImGuiIO io = getIO();
        initFonts(io);
    }
```

**Comment by SpaiR** [comment]
Please, use issue templates to create bug reports.

Speaking of your problem, it's not connected to the imgui-java. There are several examples where people successfully integrated the binding to Minecraft. You can explore for them on GitHub as well.
