### ISSUE TITLE
ImGuiIO missing NavInputs

### ISSUE THREAD

**Issue by ambye85** [SpaiR/imgui-java#12]
I'm trying to port https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_glfw.cpp with 1.76-0.13.

The `updateGamepads()` method requires accessing the `io.NavInputs` array but I cannot find a suitable `io.setNavInputs()` method.

Am I missing something obvious or do we need to add that functionality?

**Comment by SpaiR** [comment]
Yeah, I've missed that. Will add in a short time.

**Comment by ambye85** [comment]
Great. Happy to contribute as an example windowing system implementation once that's in.
