### ISSUE TITLE
ARM natives

### ISSUE THREAD

**Issue by s0larm00n** [SpaiR/imgui-java#123]
Hi! Are you are planning to add natives for Apple chip (ARM architecture)? That would be absolutely fantastic
P.S. sorry if they exist and I'm just missing something, but as far as I understand there's no support for ARM yet, tried to run a test app (extending imgui.app.Application) with a single dependency "io.github.spair:imgui-java-app:1.86.4" and getting an unsatisfied link error: "... mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')"

**Comment by SpaiR** [comment]
There is a PR which adds arm support. Yet it's incomplete. You can use it to build native arm binaries locally. Or finish the PR instead. https://github.com/SpaiR/imgui-java/pull/112
