### ISSUE TITLE
Hide GLFW window in Application

### ISSUE THREAD

**Issue by rofleksey** [SpaiR/imgui-java#124]
Is there a way to hide default GLFW window that is used for the first ImGUI window from Application class?

**Comment by SpaiR** [comment]
Not sure what is meant by "hide default GLFW window". Do you mean, like, how to create another GLFW window with ImGui?

**Comment by JDoawp** [comment]
I'm assuming they're talking about this window in red, while keeping the 'actual' GUI, the Debug + text window.

![java_3Qw7nQLk2s](https://github.com/SpaiR/imgui-java/assets/16917325/f038f691-7865-4f95-b0f4-f6fc4357bceb)

**Comment by Brohammer5** [comment]
If you see when including imgui, it makes its own grey background causing issues with other OpenGL elements. 

<img width="960" alt="Screenshot 2023-12-25 112551" src="https://github.com/SpaiR/imgui-java/assets/78236275/c8486e42-fa2c-41d1-8959-8645734e9acd">
<img width="960" alt="Screenshot 2023-12-25 115239" src="https://github.com/SpaiR/imgui-java/assets/78236275/7cfe2d81-cb7b-4449-9947-01987a83901a">

**Comment by SpaiR** [comment]
If this is a general question related to Dear ImGui, it should be addressed to the repository there. If any part of the binding API is not working correctly, please be specific and point out what is broken. Alternatively, feel free to fix the issue and submit a PR—I'd be happy to review and merge it into the repository.
