### ISSUE TITLE
ImGui renders in wrong position at half scale on retina display

### ISSUE THREAD

**Issue by ambye85** [SpaiR/imgui-java#14]
I've been using a non-hidpi monitor so have only recently noticed that when I use my retina display I get the following ImGui output:

<img width="1392" alt="Screenshot 2020-07-03 at 04 04 04" src="https://user-images.githubusercontent.com/17502031/86430996-79802880-bceb-11ea-955f-0831c197c218.png">

Should I be looking at my scale factor configuration or is it a broader problem related to https://github.com/ocornut/imgui/pull/2826?

**Comment by SpaiR** [comment]
Dear ImGui doesn't handle HiDPI scaling automagicaly, so you should do it manually. There is an official article which shows how to do that https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application

Speaking about the PR you've mentioned, I've talked to the author and he said that it won't be implemented.
![image](https://user-images.githubusercontent.com/12721311/86454316-ba962e00-bd27-11ea-9878-cfb30b137aa8.png)

From my experience I will note that approach with `pointSize` is pretty simple to implement, thus it's not a problem at all. Here is a code I've made for my editor I do https://github.com/SpaiR/StrongDMM/commit/d49ba34deaf8c4d13b2815f33c22d8ecb154162e

See the demo https://imgur.com/a/LOJsrki

**Comment by ambye85** [comment]
Thanks, I had missed that section of the document. Appreciate you sharing the example too.
