### ISSUE TITLE
Render State flag

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#15]
Greetings,

I have successfully integrated your Imgui API with Vulkan (lwjgl bindings)! My only question is there is a way for you to send me a flag that tells that the render state has changed? Given the nature of Vulkan with Imgui, I have to reset the command pool, for every frame, and redraw all the objects. This way I can save a few GPU cycles.

**Comment by SpaiR** [comment]
Hello.
I'm a little bit unsure what kind of flag do you expect. Do you mean something like that https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_vulkan.cpp#L397-L398 ? From your description I see you are expecting something from the API itself, but it's impossible. The link I've posted shows a usercallback which user still should add **manually**. No other options is available.
Could you provide an example or something which will give more details about what you're trying to achieve?
