### ISSUE TITLE
Flex layout implementation

### ISSUE THREAD

**Issue by Osiris-Team** [SpaiR/imgui-java#153]
Is there an implementation of css flexbox for this?
I find it quite annoying to give absolute coordinates and sizes to almost all my components.
https://www.w3.org/TR/css-flexbox-1/#box-model

Also it looks like I can't position text?

**Comment by SpaiR** [comment]
Unfortunately, Dear ImGui (the original library) is not built with layouts in mind. There are PR's like https://github.com/ocornut/imgui/pull/846, but as you can see from the date of its create (2016) and the fact that it's still not merged - widgets layout is not a main course of the library.

It's possible to implement stuff like that by yourself, but it's always a work from the ground. A hard work I might say.

Also, as the workaround solution you can try to use table API. It's pretty useful in situations when you need to spread items properly. Still, it's far away from functionality like flexbox though...

For the reference:
 - https://github.com/ocornut/imgui/issues/97
 - https://github.com/ocornut/imgui/issues/897
 - https://github.com/ocornut/imgui/issues/319

**Comment by Osiris-Team** [comment]
Thanks @SpaiR , that's sad to hear though.
I started working on a java flex layout implementation, using the table api like you said.
And some basic functionality is already working:
```java
        FlexLayout ly = new FlexLayout(null); // parent == null thus sets the window as its parent
        // Default alignment of FlexLayout is vertical
        ly.horizontal() // Creates a new child FlexLayout with horizontal alignment
                .text("Some ").text("text!");
        ly.vertical() // Creates a new child FlexLayout with vertical alignment
                .text("More ").text("text!");
```
If someone is interested in using/contributing, the source code for this is here:
https://github.com/Osiris-Team/BetterDesktop/tree/main/src/main/java/com/osiris/betterdesktop/utils/flex
I'll move it to a separate repo someday maybe.

**Comment by SpaiR** [comment]
@Osiris-Team You may find it interesting: https://www.reddit.com/r/java/comments/xarfpq/jvm_port_of_randrews_layout_a_simplefast_stacking/

**Comment by Osiris-Team** [comment]
Wow that looks exactly like what I was looking for! Thanks!
But the API is kind of ugly, so I'll look for inspiration and see how they did it.

**Comment by Osiris-Team** [comment]
So in the end the library is not meant to be used with imgui it seems.
I then lost it and made my own GUI library Desku available here:  https://github.com/Osiris-Team/Desku
Its uses chromium to render, thus the GUI is based on HTML/CSS/JS, however I Desku replaces the need to write in those languages and makes it possible to have a fully Java based GUI.
The main reason that I gave up imgui is, because its weird and harder to write async code that interacts with the UI.
HTML/CSS are also much more developed/flexible GUI languages, thus it makes more sense to use them.
