### ISSUE TITLE
Not possible to add multiple window flags to a new ImGui.begin() ?

### ISSUE THREAD

**Issue by Kaegra1** [SpaiR/imgui-java#154]
Hello everyone, 
I'm new to this whole github and coding thing. I'm currently trying to build an UI using ImGui on java but I'm faced with an issue :
- Adding multiple flags on an ImGui.begin()

I know it's possible on the C++ version but I can't seem to find the "translation" on java version. Is it a limitation ?

Thanks in advance for your help !
Hope I'm posting this on the right place

**Comment by SpaiR** [comment]
@Kaegra1 Hi!
Multiple flags are passed in the same manner as in C++ - with an `OR` bitwise operator:
```
if (ImGui.begin("Example", ImGuiWindowFlags.NoResize | ImGuiWindowFlags.NoMove))
    ImGui.text("Example");
ImGui.end();
```
