### ISSUE TITLE
DockSpace Doesn't follow Dear ImGui's' API

### ISSUE THREAD

**Issue by NPEX42** [SpaiR/imgui-java#16]
The Original API defines a ImGui.dockSpace() function that is not present in this binding.

**Comment by SpaiR** [comment]
Amm... :confused: 
https://github.com/SpaiR/imgui-java/blob/master/imgui-binding/src/main/java/imgui/ImGui.java#L4356-L4370
https://javadoc.io/static/io.imgui.java/binding/1.77-0.16/imgui/ImGui.html#dockSpace-int-

**Comment by NPEX42** [comment]
' There is ImGui::DockSpace() call which allows you to create an explicit docking node within an existing window. If you have a full-on editor this is useful to build your main application around a menu-bar etc. Simpler applications will be using docking functions without ever calling DockSpace(). This function comes with one fundamental constraint: anything you dock into an explicit DockSpace() node needs to be submitted after it, so you’ll have to structure your app around that one limitation. It is also generally expected that your dockspaces, if you have any, persist at all time. ' - Dear ImGUI Issue #2109

**Comment by SpaiR** [comment]
So... I still don't get you. See the links I've posted, there is a `dockSpace` method as well. Or give the link to the native "DockSpace" you're looking for.

**Comment by NPEX42** [comment]
The supplied Dockspace() functions require arguments, i may be reading the originals API wrong, but there is a no-arg version

**Comment by SpaiR** [comment]
Oh, I see. You're probably misleading yourself with the issue comment. The point is that there is no non-arg version of the `DockSpace` method. You're always should to provide and `ImGuiID`. Here is the original code to see https://github.com/ocornut/imgui/blob/docking/imgui.h#L673

Always check the original repo to see an available API.

**Comment by NPEX42** [comment]
Okay, Thank you. My apologies.
