### ISSUE TITLE
Missing Bindings: ImNodes selection methods

### ISSUE THREAD

**Issue by brunopj1** [SpaiR/imgui-java#161]
### Version

1.86.8

### What part of the binding has gaps?

ImNodes

### What is missing?

Some ImNodes bindings related to node / link selection are missing:

`ImNodes::IsNodeSelected(int);`
`ImNodes::IsLinkSelected(int);`

`ImNodes::SelectNode(int);`
`ImNodes::SelectLink(int);`
`ImNodes::ClearNodeSelection(int)`
`ImNodes::ClearLinkSelection(int)`

The first two functions aren't that important, because the same behavior can be achieved by getting the entire selection.
As for the last four functions, there is no way at the moment to manually select or deselect a node or link.

**Comment by brunopj1** [comment]
I just found out that there's another binding missing for ImNodes:

`ImNodes::PushStyleVar(int, ImVec2)`

There is a version available for pushing float variables, but the ImVec2 version is missing.

**Comment by SpaiR** [comment]
resolved in #167
