### ISSUE TITLE
Multiple Contexts

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#17]
Is there a way for you to included the following native call methods like GetCurrentContext and SetCurrentContext?
```

    // Context creation and access
    // Each context create its own ImFontAtlas by default. You may instance one yourself and pass it to CreateContext() to share a font atlas between imgui contexts.
    // None of those functions is reliant on the current context.
    IMGUI_API ImGuiContext* CreateContext(ImFontAtlas* shared_font_atlas = NULL);
    IMGUI_API void          DestroyContext(ImGuiContext* ctx = NULL);   // NULL = destroy current context
    IMGUI_API ImGuiContext* **GetCurrentContext**();
    IMGUI_API void          **SetCurrentContext**(ImGuiContext* ctx);
```
https://github.com/ocornut/imgui/blob/master/imgui.h

I need to have the ability to support multiple contexts because I'm using multiple secondary buffers in Vulkan.

**Comment by SpaiR** [comment]
Yes, it's possible. Yet `ImGuiContext` class is the part of the internal ImGui API. Which I don't support. I've partly described the reason here #7. At the moment I don't have time to do a port for it. Maybe later or someone will do it instead.

**Comment by gviznyuk** [comment]
Would you consider opening up sponsorship, then I would be willing to make a donation, so that you can continue to add enhancements?

**Comment by SpaiR** [comment]
Maybe later.

**Comment by gviznyuk** [comment]
The native binaries that you currently have, do they already contain the ImGuiContext class?  If so, I simply have to extend your native bindings, correct?

**Comment by SpaiR** [comment]
In some way that is true. Binaries are compiled with Dear ImGui, so the library do has all its structures. Yet the point of the binding is to give a communication layer. There is no class to communicate with ImGuiContext object.

**Comment by gviznyuk** [comment]
I tried to extend the ImGui.java class with my class:

`package imgui;

public final class ImGuiEXT {

    private ImGuiEXT() {
    }

    /*JNI
        #include <stdint.h>
        #include <imgui.h>
     */

    private static native long nGetCurrentContext(); /*
        if (ImGui::GetCurrentContext() == NULL)
            return 0;
        return (intptr_t)ImGui::GetCurrentContext();
    */

    public static long getCurrentContext() {
        return nGetCurrentContext();
    }

    public static void setCurrentContext(long ptr) {
        nSetCurrentContext(ptr);
    }

    private static native void nSetCurrentContext(long ptr); /*
        ImGui::SetCurrentContext((ImGuiContext*)ptr);
    */

    public static long createContext() {
        return nCreateContext();
    }

    private static native long nCreateContext(); /*
        return (intptr_t)ImGui::CreateContext();
    */

    public static void destroyContext(long ptr) {
        nDestroyContext(ptr);
    }

    private static native void nDestroyContext(long ptr); /*
        ImGui::DestroyContext((ImGuiContext*)ptr);
    */
}
`

But I'm getting java.lang.UnsatisfiedLinkError: 'long imgui.ImGuiEXT.nCreateContext()'.
What do you suggest?

**Comment by SpaiR** [comment]
You're keeping to get things wrong. -_- 
Your "extension" is do nothing, because imgui-java is built around **native** C++ library. Binding communication is done with [JNI](https://en.wikipedia.org/wiki/Java_Native_Interface). The native code itself is compiled with a special generator. In that way your code doesn't make any sense.

**Comment by gviznyuk** [comment]
Друг мой,  то что я приклеил внизу,  пожалуйста добавь этих несколько строчек в главном классе [ImGui.java]. Я еще прибавил JNI Mapping и headers.  Мне просто надо доступ к контексту, и возможность менять его на другой, для меня не важно его внутренные свойства. Буду благодарен.

```
   /*JNI
        #include <stdint.h>
        #include <imgui.h>
     */

    private static native long nGetCurrentContext(); /*
        if (ImGui::GetCurrentContext() == NULL)
            return 0;
        return (intptr_t)ImGui::GetCurrentContext();
    */

    public static long getCurrentContext() {
        return nGetCurrentContext();
    }

    public static void setCurrentContext(long ptr) {
        nSetCurrentContext(ptr);
    }

    private static native void nSetCurrentContext(long ptr); /*
        ImGui::SetCurrentContext((ImGuiContext*)ptr);
    */

    public static long createContext() {
        return nCreateContext();
    }

    private static native long nCreateContext(); /*
        return (intptr_t)ImGui::CreateContext();
    */

    public static void destroyContext(long ptr) {
        nDestroyContext(ptr);
    }

    private static native void nDestroyContext(long ptr); /*
        ImGui::DestroyContext((ImGuiContext*)ptr);
    */
```

JNI: 

```
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class imgui_ImGui */

#ifndef _Included_imgui_ImGui
#define _Included_imgui_ImGui
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     imgui_ImGui
 * Method:    nGetCurrentContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGui_nGetCurrentContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImGui
 * Method:    nSetCurrentContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGui_nSetCurrentContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     imgui_ImGui
 * Method:    nCreateContext
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_imgui_ImGui_nCreateContext
  (JNIEnv *, jclass);

/*
 * Class:     imgui_ImGui
 * Method:    nDestroyContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_imgui_ImGui_nDestroyContext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
```
```

#include <stdint.h>
#include <imgui.h>


JNIEXPORT jlong JNICALL Java_imgui_ImGui_nGetCurrentContext(JNIEnv* env, jclass obj) {
    if (ImGui::GetCurrentContext() == NULL)
        return 0;
    return (intptr_t)ImGui::GetCurrentContext();
}

JNIEXPORT void JNICALL Java_imgui_ImGui_nSetCurrentContext(JNIEnv* env, jclass obj, jlong ptr) {
    ImGui::SetCurrentContext((ImGuiContext*)ptr);
}

JNIEXPORT jlong JNICALL Java_imgui_ImGui_nCreateContext(JNIEnv* env, jclass obj) {
    return (intptr_t)ImGui::CreateContext();
}

JNIEXPORT void JNICALL Java_imgui_ImGui_nDestroyContext(JNIEnv* env, jclass obj, jlong ptr) {
    ImGui::DestroyContext((ImGuiContext*)ptr);
}
```

**Comment by perrymacmurray** [comment]
Hi @SpaiR, sorry to revive a dead issue, but for my own code I was interested in switching between multiple contexts. Is there an existing way to do something like this, or is it still unimplemented?

If a solution doesn't already exist, I'd love to give implementing context switching and maybe the internal API a shot, but I don't completely understand what other than the contexts needs to be implemented. Do you have any advice?

**Comment by SpaiR** [comment]
@perrymacmurray There is no solution, so you can implement it without any restrictions. At the moment I am more liberal about touching internal API, then before. I don't think that anything else than context structs need to be done. I even think, that you can try to go with only basic code, which holds object pointer. No need to force yourself with implementing all struct fields etc. Only stuff you need to make things work. Just keep it clean, with general code style in mind.
