### ISSUE TITLE
Implementing ImGUI in an already existing LWJGL3 enviroment

### ISSUE THREAD

**Issue by Caue-Aron** [SpaiR/imgui-java#177]
I couldn't find any example showing how to do exactly this. I'd like to just put some gui in an app i already am working on, without having to extend from Application. If possible how can i do that? Im sorry but i didnt find any resources on that.

**Comment by SpaiR** [comment]
Yes. You can basically take `ImGuiImplGlfw` and `ImGuiImplGl3` (or even copy-paste code from them) and "attach" them to your application. [Window.java](https://github.com/SpaiR/imgui-java/blob/main/imgui-app/src/main/java/imgui/app/Window.java) class shows how exactly you can do that, just follow the code.

**Comment by Caue-Aron** [comment]
I'm now trying to implement ImGui to this project tutorial: https://www.youtube.com/watch?v=f6gVind3jFQ

Although the code is quite complex to deal with, im getting memory errors everytime and i cant get things to show on screen. This is how the project is setup: https://github.com/Caue-Aron/LowPM_TEST
