### ISSUE TITLE
imgui-java breaks 

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#19]
I successfully compiled the imgui-java and generated the libimgui-java64.so. When I try to run the example demo I get this:

`/opt/idea-IU-192.7142.36/jbr/bin/java: symbol lookup error: /opt/imgui-java/imgui-java/bin/libimgui-java64.so: undefined symbol: FT_New_Library`

I have the freetype2 library linked when I compiled it, so I don't understand.

```
        linux64.cppFlags += " -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include"
        linux64.linkerFlags += " -lfreetype "
```

**Comment by SpaiR** [comment]
You're probably need to install an additional library: mingw-w64-freetype2

**Comment by SpaiR** [comment]
@gviznyuk Can you verify the problem has been solved?

**Comment by gviznyuk** [comment]
Greetings,

It has been resolved.

Thanks,
Georgii
