### ISSUE TITLE
Unable to assign / use custom ImGuiStyle

### ISSUE THREAD

**Issue by rheia777** [SpaiR/imgui-java#194]
I wanted to set a custom style, but I can't seem to find the correct method to use.
Usually you just get a pointer to the object and edit that.
Do you have to assign it somewhere else, when using these bindings?

Example code:
```java
ImGuiStyle style = ImGui.getStyle();
style.setAlpha(1.0f);
style.setDisabledAlpha(0.6000000238418579f);
style.setWindowPadding(8.0f, 8.0f);
style.getColors()[ImGuiCol.WindowBg] = new float[] {0.09803921729326248f, 0.09803921729326248f, 0.09803921729326248f, 1.0f};
// .... omitted the rest
```
When I used `ImGui.pushStyleColor(...)`, it worked, but that's obviously not what I want.

**Comment by Brohammer5** [comment]
I think you need to do ```
Imgui.popStyle()
```
in order to properly have a new style.

**Comment by SpaiR** [comment]
If this is a general question related to Dear ImGui, it should be addressed to the repository there. If any part of the binding API is not working correctly, please be specific and point out what is broken. Alternatively, feel free to fix the issue and submit a PR—I'd be happy to review and merge it into the repository.
