### ISSUE TITLE
Sometimes it works.. sometimes some unknown garbage text. sometimes crashed.

### ISSUE THREAD

**Issue by Dj-jom2x** [SpaiR/imgui-java#20]
Target: Minecraft 1.16.2
Fabric: latest

Sometimes work
![image](https://user-images.githubusercontent.com/12135498/91925881-867bc100-ed08-11ea-81e2-4bb9f77e31f5.png)
Sometimes not
![image](https://user-images.githubusercontent.com/12135498/91925893-8e3b6580-ed08-11ea-9fae-25352c0791d9.png)

heres the example code 

```java
package net.fabricmc.example.screen;

import java.util.Objects;

import imgui.ImGui;
import imgui.ImGuiIO;
import imgui.flag.ImGuiConfigFlags;
import imgui.gl3.ImGuiImplGl3;
import imgui.glfw.ImGuiImplGlfw;
import imgui.type.ImString;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.gui.screen.Screen;
import net.minecraft.client.util.math.MatrixStack;
import net.minecraft.text.LiteralText;

@Environment(EnvType.CLIENT)
public class ImguiScreen extends Screen {

	private long windowPtr;

	private final ImGuiImplGlfw implGlfw = new ImGuiImplGlfw();

	private final ImGuiImplGl3 implGl3 = new ImGuiImplGl3();

	private final ImGuiIO io;

	public ImguiScreen() {
		super(new LiteralText("ImguiScreen"));
		windowPtr = MinecraftClient.getInstance().getWindow().getHandle();
		ImGui.createContext();
		io = ImGui.getIO();
		implGlfw.init(windowPtr, false);
		implGl3.init("#version 150");
	}

	@Override
	public boolean isPauseScreen() {
		return false;
	}

	@Override
	public boolean charTyped(char chr, int keyCode) {
		if (io.getWantTextInput()) {
			io.addInputCharacter(chr);
		}
		super.charTyped(chr, keyCode);
		return true;
	}

	@Override
	public boolean keyPressed(int keyCode, int scanCode, int modifiers) {
		if (io.getWantCaptureKeyboard()) {
			if (io.getKeysDown(keyCode)) {
				io.setKeysDown(new boolean[] { true });
			}
		}
		super.keyPressed(keyCode, scanCode, modifiers);
		return true;
	}

	@Override
	public boolean keyReleased(int keyCode, int scanCode, int modifiers) {
		if (io.getWantCaptureKeyboard()) {
			if (io.getKeysDown(keyCode)) {
				io.setKeysDown(new boolean[] { false });
			}
		}
		super.keyReleased(keyCode, scanCode, modifiers);
		return true;
	}

	ImString msg = new ImString();

	@Override
	public void render(MatrixStack matrices, int mouseX, int mouseY, float delta) {
		// TODO Auto-generated method stub
		implGlfw.newFrame();
		ImGui.newFrame();
		ImGui.begin("hello");
		ImGui.text("hello");
		ImGui.inputText("Sample", msg);
		ImGui.end();
		ImGui.render();
		implGl3.renderDrawData(Objects.requireNonNull(ImGui.getDrawData()));
	}
}

```

sometimes access violation error stuff

**Comment by SpaiR** [comment]
You need to be more specific about the problem you've met.
How the "garbage text" is looks like? What kind of crash you experience? Do you have any stack trace, crash report etc.? I can't confirm that this is a binding problem from two screenshots and code example. That tells me nothing. :confused: 

From the example you've posted I can say that line `io.setKeysDown(new boolean[] { true });` will crash the program for sure. Method expects 512 size array and you've violated its contract. See how `ImGuiImplGlfw` handles keys pressing/releasing for reference and do the same: https://github.com/SpaiR/imgui-java/blob/master/imgui-lwjgl3/src/main/java/imgui/glfw/ImGuiImplGlfw.java#L131-L135

**Comment by Dj-jom2x** [comment]
> You need to be more specific about the problem you've met.
> How the "garbage text" is looks like? What kind of crash you experience? Do you have any stack trace, crash report etc.? I can't confirm that this is a binding problem from two screenshots and code example. That tells me nothing. 😕
> 
> From the example you've posted I can say that line `io.setKeysDown(new boolean[] { true });` will crash your program for sure. Method expects 512 size array and you've violated its contract. See how `ImGuiImplGlfw` handles keys pressing/releasing for reference and do the same: https://github.com/SpaiR/imgui-java/blob/master/imgui-lwjgl3/src/main/java/imgui/glfw/ImGuiImplGlfw.java#L131-L135

io.setKeysDown(new boolean[] { true });

this is the only way to make it type 1 character at a time. and it does work. I did try your suggestion and the result is same but i prefer your suggestion looks neat and proper way..

if you close open the ui sometimes it shows garbage like this 

![image](https://user-images.githubusercontent.com/12135498/91968076-b21d9c00-ed46-11ea-8be0-5258fc445638.png)

or it doesn't render at all.. then you close the screen and open it again it will work.. its like 4/10 chance u will get this display..

heresa demo gift

![ezgif-4-918517cc3abb](https://user-images.githubusercontent.com/12135498/91968319-12acd900-ed47-11ea-8949-03c4393d5fb8.gif)

**Comment by Dj-jom2x** [comment]
I added a repo for this

https://github.com/Dj-jom2x/fabric-example-mod-SpaiR

**Comment by SpaiR** [comment]
> or it doesn't render at all.. then you close the screen and open it again it will work.. its like 7/10 chance u will get this display..

If imgui is capable to be rendered at all, then I'll assume that it's mostly a problem from the game side. I'm not aware about Minecraft rendering routine, but it looks like something intersects with imgui renderer. It's strange that it works from time to time. Otherwise I would suggest to try another shader version.

Also take a note that if you're using an imgui-java renderer/backend, then LWJGL 3.2.3 is used there. AFAIK minecraft uses another version of this lib. That could be an issue as well. You may try to copy&paste both `ImGuiImplGl3` and `ImGuiImplGlfw` classes into your codebase. Then you need to remove this dependency https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/blob/master/build.gradle#L30 and provide lwjgl dependencies with the version used in minecraft.

> I added a repo for this

I will be glad to help to resolve problems from the binding side, but I'm not feel to learn Minecraft modding environment. If you'll find something specific feel free to post about that.

**Comment by Dj-jom2x** [comment]
yeah I have a quest to have working mc demo using https://github.com/SpaiR/imgui-java and https://github.com/kotlin-graphics/imgui/  

the `kotlin-graphics/imgui/` is 100% done I already solve my problem with it..

I kinda want to make this thing work here also because your bindings are very close to the original. I will try your suggestion and see what will happen.

**Comment by SpaiR** [comment]
> and use mc internal lwjgl

That will be even better. The point is to try to use the same lwjgl as mincraft does. No matter how it will be provided.

**Comment by Dj-jom2x** [comment]
ok, I did that dint help I'm so sad. u can see the other addons in https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/tree/master/src/main/java/net/fabricmc/example/imgui

also added proper destroying context on close.

and using #version 330 shader

**Comment by Dj-jom2x** [comment]
sometimes I have this when I close open it many times xD

![image](https://user-images.githubusercontent.com/12135498/91997828-14899300-ed6d-11ea-86b4-7d7de9223e10.png)

**Comment by SpaiR** [comment]
Hmm... I see. Is `ImguiScreen` (or even `net.fabricmc.example.screen.Screen`) a singleton object? I mean, if it's created every time you open the window (and it seems like it does) - that could be a problem. 

Those lines should be called only once https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/blob/master/src/main/java/net/fabricmc/example/screen/ImguiScreen.java#L36-L39 You can add a static variable `isImGuiInitialized` and check it in the constructor to do things only once per application run. You don't need to do a destroy in `onClose`. Only when application is shutting down.

Those should be static as well https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/blob/master/src/main/java/net/fabricmc/example/screen/ImguiScreen.java#L25-L29

**Comment by Dj-jom2x** [comment]
> Hmm... I see. Is `ImguiScreen` (or even `net.fabricmc.example.screen.Screen`) a singleton object? I mean, if it's created every time you open the window (and it seems like it does) - that could be a problem.
> 
> Those lines should be called only once https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/blob/master/src/main/java/net/fabricmc/example/screen/ImguiScreen.java#L36-L39 You can add a static variable `isImGuiInitialized` and check it in the constructor to do things only once per application run. You don't need to do a destroy in `onClose`. Only when application is shutting down.
> 
> Those should be static as well https://github.com/Dj-jom2x/fabric-example-mod-SpaiR/blob/master/src/main/java/net/fabricmc/example/screen/ImguiScreen.java#L25-L29

The screen will render if you open it and destroy on close.. yeah, its created like fresh-baked potato ..

**Comment by SpaiR** [comment]
So you should try to rewrite it as I suggested in message before. Render is fine, but initialization and destroying is could be done only once. It's also preferable from the performance perspective.

**Comment by Dj-jom2x** [comment]
the result is the same :( but this time instead of going back to broken render to fully render randomly.. its stays broken.

![image](https://user-images.githubusercontent.com/12135498/92194211-b65bcd80-ee9c-11ea-9d43-3080eb5b72b6.png)

**Comment by SpaiR** [comment]
So I've got my hands to your example. And it works just fine for me. I've found out that there are problems when I'm enabling video record soft before the library has been initialized, so I've moved your `global.boot()` to the `ExampleMixin` init method. In order to save input between window opening I've made `ImString msg` field static. Here is the demo:

https://i.imgur.com/6oPgFCP.mp4

**Comment by SpaiR** [comment]
I'm closing the issue since it is not connected with the binding but with the codebase of the mod itself. There are minor and major problems which should be fixed there as well.

**Comment by Dj-jom2x** [comment]
yeah moving the boot to ExampleMixin fix it. you can add this to the wiki now I guess for demo.. btw thanks...
