### ISSUE TITLE
Git Clone

### ISSUE THREAD

**Issue by Joe0132134** [SpaiR/imgui-java#210]
Trying to clone git@github.com:SpaiR/imgui-java.git causes a "publickey" error,
https://github.com/SpaiR/imgui-java.git works.

**Comment by SpaiR** [comment]
This is a local git configuration problem. You're missing configured ssh keys, I guess. [link](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/Fix-GitHubs-Permission-denied-publickey-SSH-error#:~:text=GitHub's%20Permission%20denied%20(publickey)%20error,used%20by%20the%20secure%20shell)
