### ISSUE TITLE
Porting of ShowDemo_RealtimePlots over Java

### ISSUE THREAD

**Issue by SolsticeSpectrum** [SpaiR/imgui-java#219]
### Version

v1.86.11

### What part of the binding has gaps?

ImPlot

### What is missing?

Hello, I spent several hours on this already but I am failing at porting this real time plot demo. I wanna use it for profiling but both `plotLine` and `plotShaded` require arrays instead of floats so I am not entirely sure how to translate this. Also the C++ implementation uses negative infinity for ys which I am not sure how to do that with arrays. 

Maybe implement those two functions with floats as alternative? Because clearly the original can do that.

https://github.com/epezent/implot/blob/dea3387cdcc1d6a7ee3607f8a37a9dce8a85224f/implot_demo.cpp#L716C9-L716C9

I tried something like this but it crashes https://pastebin.com/N59YhGWE

Maybe adding all those examples as well so we actually know how to write this in Java would be helpful

**Comment by SpaiR** [comment]
I've tested your provided code on PR #240, and it doesn't crash. The problem still exists, but in the sense that the plots are not rendering anything properly. However, this is an issue with the API usage.

**Comment by SolsticeSpectrum** [comment]
You added the Java equivalent of the cool plot demos and other demos or you just made it so all functions match the originals?

**Comment by SpaiR** [comment]
I ran the code example you provided, and it doesn't crash. That's the main indicator for me. The fact that the plots aren't displaying anything meaningful is an issue with the API usage.

Regarding the methods themselves—yes, the API is now more complete and allows you to call all the main ImPlot methods as they are in the original. You can try to replicate your specific example in the `example` module of `imgui-java`, or wait for the next release (which will be soon) to test the code in your project.

If any new problems or errors arise, they should be addressed in a separate issue.
