### ISSUE TITLE
Easier binding generations

### ISSUE THREAD

**Issue by Desoroxxx** [SpaiR/imgui-java#228]
Have you looked into this: https://github.com/dearimgui/dear_bindings

It's official and could help making it easier to generate java bindings 

You most likely already are aware of it but i wanted to create this issue just in case.

**Comment by SpaiR** [comment]
Yes, I have studied that repository. However, the approach it uses to create metadata for binding seemed unsuitable to me. In PR #240, I added something similar—a mechanism for generating complete AST trees from the given source files. This implementation seems more flexible to me, as it can work with any C++ sources.

Nevertheless, thank you for bringing this to my attention. I appreciate any help. 🙏
