### ISSUE TITLE
Bug: ImFontAtlas' ClearInputData method crashes without any error.

### ISSUE THREAD

**Issue by Mjrlun** [SpaiR/imgui-java#229]
### Version

1.86.11

### What happened?

Upon calling the method in the title, the JVM hangs and hard-crashes with no outputted error.

What I expected to happen is the font atlas to clear the input data.

I've tried to find a solution online for week, still can't find one.

### Reproduction

_This method splits all of the clear() methods in order to make sure none of them break. Hopefully once this is solved, I'll switch back to the generic version. Yes, the same error occurs with clear(), so this may be an imgui issue, rather than with the binding._
![image](https://github.com/SpaiR/imgui-java/assets/84252662/932f3f83-d987-4040-98c5-a6bd1fe4ebad)
Upon starting the program, the font atlas is cleared (for code generality reasons). This has no effect; the method returns normally.
However, upon fully loading a font, and then calling `clearInputData()` (font pointer still fully valid), the JVM crashes with no logged error. However, the behavior is very similar to a typical JVM crash in that it immediately terminates the process (leaving loggers not able to communicate).

### Relevant log output

_There is no error to report, sadly._

_**If this error is resolved as not a fault of the binding, I will bump it to the ImGUI issue tracker**_

**Comment by SpaiR** [comment]
@Mjrlun Apologies for the delayed response. I've recently started working more closely on the library and I'm reviewing the list of reported issues. 

Would it be possible for you to provide a more complete code example that reproduces the issue, preferably within the `Application` context if possible? Also, could you check if the problem still occurs with the latest versions? It's possible the issue has already been resolved.
