### ISSUE TITLE
Library crashes upon invocation of certain functions.

### ISSUE THREAD

**Issue by aeris170** [SpaiR/imgui-java#24]
I've succesfully installed the library using Maven. Tried to run the example in [here](https://github.com/SpaiR/imgui-java/tree/master/imgui-lwjgl3/src/test/java) but the program crashes when it hits these functions: 

`ImGui#setConfigViewportsNoTaskBarIcon(boolean);` (Line 150)
`ImFontConfig#setMergeMode(boolean);` (Line 166 & 171)
`ImFontConfig#setPixelSnapH(boolean);` (Line 167 & 172)

Here is the crash message:
![Screenshot 2020-09-24 115904](https://user-images.githubusercontent.com/25724155/94124171-5cc43e80-fe5d-11ea-8ff6-231001f8fea0.png)

---------

Also, although unrelated, when invoking the `ImFontAtlas#addFontFromFileTTF(String, float, ImFontConfig)`, I have to give the string "src/main/resources/Righteous-Regular.ttf" instead of "/Righteous-Regular.ttf". I'd normally give the latter to "load from file system" functions but it doesn't work. Why does that happen? (for example ImGuiGlfwExample#loadFromResources(String) takes the latter and works).

**Comment by SpaiR** [comment]
The crash message you've provided says that it can't find a font file. That can't be related with `ImGui#setConfigViewportsNoTaskBarIcon(boolean);` by defenition. I can't say what's your problem without seeing of the full crash report.

> Also, although unrelated, when invoking the ImFontAtlas#addFontFromFileTTF(String, float, ImFontConfig), I have to give the string "src/main/resources/Righteous-Regular.ttf" instead of "/Righteous-Regular.ttf". I'd normally give the latter to "load from file system" functions but it doesn't work. Why does that happen? (for example ImGuiGlfwExample#loadFromResources(String) takes the latter and works).

`addFontFromFileTTF` loads fonts from file system relatively to the place you've started the app (or by absolute path). In places when you see a usage of `loadFromResources` method fonts are loaded with `addFontFromMemoryTTF` function. Thus `loadFromResources` just extracts fonts from jar resources and loads them into the memory. Example shows both ways of making things.

Consider to read an official wiki: https://github.com/ocornut/imgui/blob/master/docs/FONTS.md#font-loading-instructions Binding works in the same way.

**Comment by aeris170** [comment]
Where can I find the full crash report?

**Comment by aeris170** [comment]
Here is a gif proving the library crashing at the mentioned functions. Sorry for the quality.

https://media.giphy.com/media/ME08YpRpLg47UueXuw/giphy.gif

**Comment by SpaiR** [comment]
> Where can I find the full crash report?

It depends from the crash type. For JVM and native code there are different types of reports. In both cases see a console output.

You're copy-pasting an example code, but you didn't copy assets it uses. It will crash for sure. :confused: 

Read  https://github.com/SpaiR/imgui-java#how-to-try section. There're three lines of commands to call to start the example. If you're adopting it to your codebase/buildsystem and getting errors, then you need to fix them on your side.

**Comment by aeris170** [comment]
I've copied the fonts in [here](https://github.com/SpaiR/imgui-java/tree/master/imgui-lwjgl3/src/test/resources), were there any other assets I've missed? I can launch the demo fine with the mentioned lines commented out. When I uncomment them it crashes. See the image below, it loaded the fonts correctly (I commented the aforementioned lines).

![image](https://user-images.githubusercontent.com/25724155/94158278-e3dbdb80-fe8a-11ea-99b2-392ec3876c2a.png)

**Comment by SpaiR** [comment]
Hmm.. Then I'm not sure. Logs are still needed.

**Comment by aeris170** [comment]
I have no idea what I did but after I took that screen shot, I uncommented the lines and launched the demo again to copy-paste the console output. It started working, but why??

**Comment by aeris170** [comment]
I guess we can close this issue. I'll re-open if I can find any clues as to why this strange behavior happened. Sorry for wasting your time 😄.

**Comment by aeris170** [comment]
Side-note: PROBABLY I made a mistake copying/pasting stuff from here to my IDE. But this still doesn't make sense as it can be observed from the gif I've posted. Computers, you can never understand them 🤷🏿‍♂️.
