### ISSUE TITLE
Include ImPlot

### ISSUE THREAD

**Issue by calvertdw** [SpaiR/imgui-java#27]
Tl;DR This is a big ol' feature request.

What about including bindings for https://github.com/epezent/implot?

Should Java bindings for it be included in a separate project?

P.S. Thanks for working on this library. I've been using it and it's working very well! Absolutely love it.

**Comment by SpaiR** [comment]
I'm ok with that idea. The best solution will be to keep it in a separate module, so it will be optional. Even if it's impossible to organize things in that way, I'm ok if it will be a part of the main module. In terms of size it won't have a big impact on a resulted binary file.

The thing is, I personally won't do it. I have neither time, nor personal necessities in such functionality. So someone need to do it instead. Binding itself has nothing special with JNI, the hardest part there is auto-generated. Existed code could be used as example.

**Comment by SpaiR** [comment]
#56
