### ISSUE TITLE
Bug: Texture id incorrect values

### ISSUE THREAD

**Issue by lwjglgamedev** [SpaiR/imgui-java#271]
### Version

1.87.4

### What happened?

Since 1.87.4, now accepts long values for texture identifiers, I was trying to pass Vulkan descriptor sets as ids. The issue, is that if the id is long enough (I suspect if it is larger than 31 bits), the value you get when rendering seems not to be correct.

### Reproduction

Try to create an image with a long vale as its id, for example:

```ImGui.image(2459872493637207089L, new ImVec2(300, 300));```

The value you get when retriving it using:

```long id= imDrawData.getCmdListCmdBufferTextureId(i, j);```

is: 1073

**Comment by lwjglgamedev** [comment]
Didn't see it before, but should'nt the `getCmdListCmdBufferTextureId` from `ImDrawData` class, return a long?

**Comment by SpaiR** [comment]
> Didn't see it before, but should'nt the `getCmdListCmdBufferTextureId` from `ImDrawData` class, return a long?

Yes, I believe that's exactly the issue. These methods were written manually, so the conversion from `int` to `long` for textures was overlooked in this case. I think I'll implement a fix soon.

**Comment by lwjglgamedev** [comment]
Great! Thank you

**Comment by SpaiR** [comment]
The fix is already available in version 1.87.5. Please check if it's working properly for you.
