### ISSUE TITLE
Question regarding polling keyboard inputs, for example isKeyPressed()

### ISSUE THREAD

**Issue by Kazsilop** [SpaiR/imgui-java#28]
The ImGui.java file states
```
    // Inputs Utilities: Keyboard
    // - For 'int user_key_index' you can use your own indices/enums according to how your backend/engine stored them in io.KeysDown[].
    // - We don't know the meaning of those value. You can use GetKeyIndex() to map a ImGuiKey_ value into the user index.
```

This seems to imply I would need to forward keyboard inputs to ImGui from my engine, then poll isKeyPressed() using the appropriate indices.

However, given that ImGui is able to provide text input out of the box, I was wondering if there was a way to poll the keyboard without doing so? Or is it the case that ImGui is able to detect and process keyboard input, but does not have a mapping of key names to integers, hence I would need to define this mapping myself?

P.S. Thank you for creating this binding, I'm finding it stable and very straightforward to use with my libGDX projects! 👍

**Comment by SpaiR** [comment]
Dear ImGui is a platform agnostic library, so it knows nothing about its environment. Thus you need to provide that information manually. There are many examples of how to do that. https://github.com/SpaiR/imgui-java/blob/master/imgui-lwjgl3/src/main/java/imgui/glfw/ImGuiImplGlfw.java#L98-L153 I assume that libGDX has a mechanism to provide those callbacks, so it should be easy to implement.

Also, there is a wiki page which shows how to integrate the binding with libGDX: https://github.com/libgdx/libgdx/wiki/ImGui-Bindings-And-3D-Graphics I've didn't try it by myself, but I think it should work properly.

**Comment by Kazsilop** [comment]
Thanks for the clarification and the links!

I've already got everything set up in a similar manner, but I just wanted to check that there wasn't a more elegant solution.
