### ISSUE TITLE
Can't import imgui.Imgui?

### ISSUE THREAD

**Issue by Whop42** [SpaiR/imgui-java#31]
![image](https://user-images.githubusercontent.com/66795817/110012170-1eb52b80-7cd5-11eb-8c49-a246db53ad61.png)

I'm using the latest jar (https://github.com/SpaiR/imgui-java/releases/download/v1.81.1/imgui-app-1.81.1.jar)

**Comment by SpaiR** [comment]
It's not `imgui.imgui`, it's `imgui.ImGui`. 😕
