### ISSUE TITLE
Empty command list when imgui.ini present

### ISSUE THREAD

**Issue by lwjglgamedev** [SpaiR/imgui-java#33]
Hi,

I'm facing a strange issue with this library. I'm doing some tests, and it seems that once the imgui.ini file is created, the commands list is always `0`  and the buffers are not populated. I've tried to create a simple sample to show this. The folloing code just initializes Imgui, creates the demo window, renders it and then tries to get the commands list.
```java
package org.vulkanb;

import imgui.*;
import imgui.type.ImInt;

public class TestImGui {
    public static void main(String[] args) {
        try {
            ImGui.createContext();

            ImGuiIO imGuiIO = ImGui.getIO();
            imGuiIO.setDisplaySize(1280, 720);
            imGuiIO.setDisplayFramebufferScale(1.0f, 1.0f);

            ImInt outWidth = new ImInt();
            ImInt outHeight = new ImInt();
            imGuiIO.getFonts().getTexDataAsAlpha8(outWidth, outHeight);

            ImGui.newFrame();
            ImGui.showDemoWindow();
            ImGui.render();

            ImDrawData imDrawData = ImGui.getDrawData();

            System.out.println("Cmd Lists=" + imDrawData.getCmdListsCount());
            System.out.println("Total vertices count=" + imDrawData.getTotalVtxCount());
            System.out.println("Total indices count=" + imDrawData.getTotalIdxCount());
            System.out.println("Draw data valid=" + imDrawData.getValid());

            ImGui.destroyContext();
        } catch (Exception excp) {
            excp.printStackTrace();
        }
    }
}
```

The first time it ies ececuted, no imgui.ini file is present, I get the following result:
```
Cmd Lists=1
Total vertices count=814
Total indices count=1365
Draw data valid=true
```

However, if I execute the example again, the imgui.ini is present, I get the following output:
```
Cmd Lists=0
Total vertices count=0
Total indices count=0
Draw data valid=true
```

I'm using `openjdk 15.0.2 2021-01-19` and version `1.81.2` of the imgui-java library.

Any idea of what I am missing? In addition to that, it seems to mee that the vertex coordinates have quite small values (the display size seems not to be applied). I don't know if this related to this issue or not.

Any guidance is very much appreciated.

**Comment by SpaiR** [comment]
Hi. Thanks for you detailed explanation and code example. I've didn't meet such problem. I've never tried to experiment with things in such way though.

It seems you have the same issue described here: https://github.com/ocornut/imgui/issues/1905
Specificaly, in another issue there is a comment: https://github.com/ocornut/imgui/issues/1893#issuecomment-399102821

> I see. Dear ImGui can't give you guarantee that things will appear on the first frame unless you explicitly size them. If you want to hold on a pre-recorded command buffer (which seems a little odd) maybe you can call the imgui NewFrame/Render set twice before turning the ImDrawData structure into a command buffer? 

Is it related?

**Comment by lwjglgamedev** [comment]
Thanks a lot!

Thanks to your comments, I've first being able to disable imgui.ini file generation (I don't want this), and the first problema solved. Woth the #1893 issue, I now set the size and the values of the vertex buffer start to make sense. Now I hope to start seeing something in Vulkan.

I will close the issue. Thanks again.
