### ISSUE TITLE
how do you make inputtext  accept any lenght of input

### ISSUE THREAD

**Issue by atorralb** [SpaiR/imgui-java#40]
I'm using the below code to type into the input text box;

`ImGui.inputText("default",  new imgui.type.ImString("test"), 32);`

but it just lets me write 4 characters instead of 32,,,, which is the correct way?

**Comment by SpaiR** [comment]
The third argument is input flags, not the length of the string. Please, take a time to read through the original Dear ImGui source code https://github.com/ocornut/imgui/blob/master/imgui.h. It has a pretty clear documentation about how to do things. Or at least binding javadoc...

Speaking about javadoc, see https://javadoc.io/doc/io.github.spair/imgui-java-binding/latest/imgui/type/ImString.html
You can define input string length in constructor. To make it resiziable you can change its input data or provide `ImGuiInputTextFlags.CallbackResize` flag to input itself.

But most importantly, you're doing things aboslutly wrong. Immediate Mode gui updates every frame, so every frame you create a new `ImString` object. As a result, you'll never get any input. See binding example for more reference https://github.com/SpaiR/imgui-java/blob/master/example/src/main/java/Main.java

**Comment by atorralb** [comment]
thanks alot, working as expected... I had completely forgot about the example in Main.java. 
Thanks alot for clarifying :)
Have an awesome weekend
