### ISSUE TITLE
NIOBuffer or address arguments for interactive widgets

### ISSUE THREAD

**Issue by dembanakh** [SpaiR/imgui-java#44]
As LWJGL3 introduced more efficient stack and off-heap memory buffers, it would be convenient to use those sometimes instead of allocating heap Im_type_ or _type_[]. As an example (maybe a bit artificial), I would like to do
```
FloatBuffer lengthBuffer = MemoryUtil.memAllocFloat(1);
lengthBuffer.put(length).flip();
if (ImGui.dragFloat("Length", MemoryUtil.memAddress(lengthBuffer)) {
    // update length
}
```
or even
```
try (MemoryStack stack = MemoryStack.stackPush()) {
    FloatBuffer coordsBuffer = stack.floats(z, y, x);
    if (ImGui.dragFloat("X", stack.getPointerAddress()) {
        // update x
    }
    if (ImGui.dragFloat("Y", stack.getPointerAddress() + 4) {
        // update y
    }
    if (ImGui.dragFloat("Z", stack.getPointerAddress() + 8) {
        // update z
    }
}
```

**Comment by SpaiR** [comment]
The point is that most of the time you don't need to allocate objects for every widget. If you have a desire to optimize memmory usage, your example could be re-written in the next way:
```
class ImGuiStack {
	public static final ImFloat FLOAT = new ImFloat();
}

void foo() {
	ImGuiStack.FLOAT.set(oldX());
	if (ImGui.dragFloat("X", ImGuiStack.FLOAT) {
        updateXwithNewValue(ImGuiStack.FLOAT.get());
    }
    ImGuiStack.FLOAT.set(oldY());
    if (ImGui.dragFloat("Y", ImGuiStack.FLOAT) {
        updateYwithNewValue(ImGuiStack.FLOAT.get());
    }
    ImGuiStack.FLOAT.set(oldZ());
    if (ImGui.dragFloat("Z", ImGuiStack.FLOAT) {
        updateZwithNewValue(ImGuiStack.FLOAT.get());
    }
}
```
This will be much readable, than using of LWJGL buffers.

Passing of native pointers into interactive widgets has its point, but solution, as for me, looks a bit overcomplicated. Maybe in future I will consider about such API, but not until binding-generator will be complited.

**Comment by dembanakh** [comment]
OK, I see your point, and agree in general. There is a lot of passing data back and forth, but indeed these are just primitives, no problem. Though, I am definitely looking forward to such an API extension.
Thanks
