### ISSUE TITLE
ImFontGlyphRangesBuilder bindings/reimplementation 

### ISSUE THREAD

**Issue by abvadabra** [SpaiR/imgui-java#45]
A couple of weeks ago I was working on font-awesome integration in our project and found out that imgui-java currently lacks bindings for ImFontGlyphRangesBuilder. Fortunately, it's a fairly simple utility class which can be easily reimplemented in java, and so I did, but it still feels like something which should be a part of the library.  

I am willing to make a PR but wanted to ask if you think it should be an actual bindings or java reimplementation. I also would be willing to add an example of font-awesome integration (with ImFontGlyphRangesBuilder usage) in the demo application but only if you think it will be of any benefit for the project.

p.s. tried to contact you on discord but unable to send messages for some reason.

**Comment by SpaiR** [comment]
If it's comparable easy to implement it in Java, then let it be in Java. I already have similar helper class: `ImColor`, so this is fine.
Having any kind of demo about fonts usage will be great.
