### ISSUE TITLE
Can't build natives on mac os 11.2.3

### ISSUE THREAD

**Issue by RaphiMC** [SpaiR/imgui-java#47]
This errors occurs when trying to build the natives for mac: https://pastebin.com/q0UtvXKn

**Comment by SpaiR** [comment]
Nothing platform specific here. Your gradle tries to download lombok-plugin from bintray, which is unavailable. I don't know why he do that. On every OS (CI also builds Mac) it works just fine. I assume you've changed somehow build scripts, or else... You can probably try other versions of lombok-plugin. No other thoughts about that.

**Comment by RaphiMC** [comment]
I did not modify any of the build scripts, I cloned the repository with all the submodules and executed the build command.
I am trying it again later today on another mac and will close the issue if it works there.

**Comment by SpaiR** [comment]
Then please try the latest version of lombok-plugin. I think because of JCenter shutdown they've moved their jars to maven, but, for some reason, your system cached something improperly. Or I don't know... However, if it will help, we can update it in the library as well. The latest one is https://plugins.gradle.org/plugin/io.freefair.lombok

**Comment by SpaiR** [comment]
@RaphiMC lomok plugin has been updated. Can you check if the problem still exists or gone?

**Comment by RaphiMC** [comment]
I now get this error:
![grafik](https://user-images.githubusercontent.com/50594595/117153625-73e7e900-adbb-11eb-9fb3-3d77509e7c85.png)
I installed java from the oracle java download page and it doesn't seem to work.
I don't know much about using mac osx, so if you know a fix then I can try it again. Else this issue can be closed.

**Comment by SpaiR** [comment]
No ideas. You need to find it out by yourself.

**Comment by RaphiMC** [comment]
Found a fix, now the natives build without problems.
