### ISSUE TITLE
java.lang.UnsatisfiedLinkError when adding new native methods

### ISSUE THREAD

**Issue by RaphiMC** [SpaiR/imgui-java#48]
I tried to add a new native method in ImNodes.java (for testing around).
Thats how the file looks: https://prnt.sc/1236qfd

If I build it with the command in the README and then run the example I get following error: https://prnt.sc/1236sso
The example builds and runs if I remove my own method.

Would appreciate if you can tell me how I can add java wrappers for new ImGUI addons.

**Comment by SpaiR** [comment]
Yeah, I made so example runs through the "application" plugin, but the proper way of running with local libs should be added. Basically, we need to pass `-Dimgui.library.path=path/to/local/libs` into `run` command here https://github.com/SpaiR/imgui-java/blob/master/example/build.gradle#L17-L21. You can try to resolve this problem by yourself or wait until I'll manage to find time to do that.

**Comment by RaphiMC** [comment]
Yes that fixed the issue!
