### ISSUE TITLE
Which one to download?

### ISSUE THREAD

**Issue by ghost** [SpaiR/imgui-java#52]
I'm really confused. I only wanted to use imgui-app, but the jar imgui-app-1.82.2.jar seems not enough.

**Comment by SpaiR** [comment]
`imgui-app` should be enough. Why do you think it isn't? Look at the example module. There is only one dependency to`imgui-app`.

**Comment by CretinHo** [comment]
> `imgui-app` should be enough. Why do you think it isn't? Look at the example module. There is only one dependency to`imgui-app`.

Have a look at this example code:

`import imgui.ImGui;
import imgui.app.Application;

public class Main extends Application {
    @Override
    protected void configure(Configuration config) {
        config.setTitle("Dear ImGui is Awesome!");
    }

    @Override
    public void process() {
        ImGui.text("Hello, World!");
    }

    public static void main(String[] args) {
        launch(new Main());
    }
}`

You see, it also import imgui.ImGui, don't you? Without this import, ImGui.text will definitely not work. Also, where is Configuration defined? The Configuration class in imgui-app definitely not accepted, type mismatch. Thanks.

**Comment by SpaiR** [comment]
I see. The idea was that `imgui-app.jar` will be like the only dependency to run the app. And it is actually does, but only when using maven/gradle. The jar itself doesn't include imgui/lwjgl. I'll fix it in future release and will make it a proper fatjar. Until then, if you're using raw jars, you should also add other dependecies, like: imgui-java, imgui-lwjgl3 and lwjgl itself. Or follow the video https://youtu.be/Xq-eVcNtUbw

**Comment by SpaiR** [comment]
Let it be open until I'll fix the problem.
