### ISSUE TITLE
NoClassDefFound when using with 1.16.5 fabric, glfw

### ISSUE THREAD

**Issue by 0x150** [SpaiR/imgui-java#58]
So basically, this has been bugging me for quite some time and I dont know what's wrong.
Here is the code I'm using to initialize and use imgui:
```
public class TestGUI extends Screen {

    ImGuiImplGlfw guiGlfw = new ImGuiImplGlfw();
    ImGuiImplGl3 guiOGl = new ImGuiImplGl3();

    public TestGUI() {
        super(Text.of(""));
    }

    @Override
    protected void init() {
        super.init();
        ImGui.createContext();
        guiGlfw.init(FrostClient.client.getWindow().getHandle(),false);
        guiOGl.init("#version 110");
    }

    @Override
    public void render(MatrixStack matrices, int mouseX, int mouseY, float delta) {
        guiGlfw.newFrame();
        ImGui.newFrame();
        if(ImGui.begin("yourMom")) {
            // TODO: 31.05.21 add stuff later 
        }
        ImGui.end();
        ImGui.render();
        guiOGl.renderDrawData(ImGui.getDrawData());

        super.render(matrices, mouseX, mouseY, delta);
    }
}
```

should work fine, right? Considering I implement imgui like this in build.gradle:
```
implementation "io.github.spair:imgui-java-binding:$imguiVersion"
implementation "io.github.spair:imgui-java-lwjgl3:$imguiVersion"
implementation "io.github.spair:imgui-java-natives-windows:$imguiVersion"
```
and `1.82.2` is the imgui version I'm using.
Now, here is the issue.

On `guiGlfw.newFrame();`, the program abruptly crashes with a NoClassDefFoundError exception. Here the full stacktrace: 
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class imgui.ImGui
	at imgui.glfw.ImGuiImplGlfw.newFrame(ImGuiImplGlfw.java:275) ~[imgui-java-lwjgl3-1.82.2.jar:?]
	at me.zeroX150.frost.features.gui.TestGUI.render(TestGUI.java:30) ~[main/:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer.java:616) ~[minecraft-1.16.5-mapped-net.fabricmc.yarn-1.16.5+build.9-v2.jar:?]
	... 11 more
```
it works fine for a friend, but for some reason it just fails for me, and I have no idea why. Any suggestions on what I could try to fix this?

**Comment by SpaiR** [comment]
I don't code for minecraft and the  binding itself is not about it, so I can't help you. Yet I know that imgui-java is used in some minecraft mods. Like https://github.com/MrManiacc/Blueprints or https://github.com/zeroeightysix/KAMI. You can use them as  examples.

Also, I've already told some concerns about usage with fabric here #20. You may find some useful info there.
