### ISSUE TITLE
Binaries for arm64 (windows/macos)

### ISSUE THREAD

**Issue by tlf30** [SpaiR/imgui-java#59]
Would it be possible to get binaries (as in packages as part of the releases on maven central) for both Windows and MacOS for arm64?

Thanks,
Trevor

**Comment by tlf30** [comment]
Also, I see that the 32 bit binaries did not get updated to v1.83.0.

**Comment by SpaiR** [comment]
I build binaries with CI, so if someone will do a proper arm configuration I don't see any problems to provide them as well.

32bit binaries are out of support. They require unjustifiable effort to build with freetype. You can still build them locally though.
