### ISSUE TITLE
Failing to find mac natives on jcenter

### ISSUE THREAD

**Issue by MrManiacc** [SpaiR/imgui-java#6]
Hi again, sorry to bother you, but upon trying to add the native bindings for mac, gradle fails to find the jar. I thought this was user error, but it seems they aren't present in the actual [jcenter repo](https://jcenter.bintray.com/io/imgui/java/)? Maybe it's a cache issue and will be resolved with time? Regardless gradle is failing to find the natives at the moment with the following error `Could not resolve all files for configuration ':modules:ide:runtimeClasspath.
   > Could not find io.imgui.java:natives-macos:1.76-0.11.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/io/imgui/java/natives-macos/1.76-0.11/natives-macos-1.76-0.11.pom
       - https://jcenter.bintray.com/io/imgui/java/natives-macos/1.76-0.11/natives-macos-1.76-0.11.pom'

**Comment by MrManiacc** [comment]
Weird part is I can download and view them from [here](https://bintray.com/spair/io.imgui.java/natives-macos) not sure if it's just taking time to reflect on jcenter or what is going on, this may just be me being dumb here

**Comment by MrManiacc** [comment]
Hm seems i've found a temporary fix by adding the following to my repositories: 
` maven {
        url  "https://dl.bintray.com/spair/io.imgui.java" 
    }`

**Comment by SpaiR** [comment]
Meh.. I've forgot that publishing should be done manually. Fixed.
