### ISSUE TITLE
Support for aarch64 binaries

### ISSUE THREAD

**Issue by HilbertCurve** [SpaiR/imgui-java#60]

**Comment by SpaiR** [comment]
Same as for #59, support will be only after someone will add it.

**Comment by HilbertCurve** [comment]
How did you compile ~/imgui-java/bin/libimgui-java64.so? Looking for:

- Program used: I'm assuming GCC?
- How you did it: I've never really compiled C/C++ before.

**Comment by SpaiR** [comment]
https://github.com/SpaiR/imgui-java#how-to-build-native-libraries

**Comment by HilbertCurve** [comment]
Pull request potentially solving part of this issue: 
[https://github.com/SpaiR/imgui-java/pull/61](url)
