### ISSUE TITLE
Add PushMultiItemsWidths

### ISSUE THREAD

**Issue by KennyProgrammer** [SpaiR/imgui-java#63]
Its will be very useful for me. 

I first wanted to try to write code directly in Java, but in C++ ImGui there is also` ImGuiContext` and `ImGuiWindow/ImGuiWindowClass `in which I need to get win32 `DC` (device context) and through it `ItemWidth` as well as `ItemWidthStack`. I just used this function in C++ before, but now I'm writing in Java and I'm wondering how it will look on it. And is it even possible to somehow get the `ImGuiContext` from via `JNI`? In the same place, it seems like if you need a `DC`, then we need to get through to the Win32 API.

**Comment by SpaiR** [comment]
`ImGuiContext` is the part of the internal API, so it's not implemented in the binding. It's not hard to implement it though.
