### ISSUE TITLE
dragInt3 only shows 2 boxes?

### ISSUE THREAD

**Issue by BBonless** [SpaiR/imgui-java#68]
When using ImGui.dragInt3 like so for example:

```java
int[] TestArray = new int[3];
ImGui.dragInt3("Test", TestArray);
```

The result is identical to a dragInt2, there are only 2 boxes available.

![image_2021-07-26_225406](https://user-images.githubusercontent.com/50674795/127057699-65401e73-ff88-4657-935a-7726a6b97f96.png)

**Comment by SpaiR** [comment]
Yeah, there is a mistake in the binding API and instead of calling `DragInt3` method calls `DragInt2`. That could be easily fixed.
https://github.com/SpaiR/imgui-java/blob/master/imgui-binding/src/main/java/imgui/ImGui.java#L2095-L2113

**Comment by BBonless** [comment]
Ah I see, thanks :)

**Comment by SpaiR** [comment]
It's still an issue until someone will resolve the problem. Let it to be open.
