### ISSUE TITLE
Possibly missing `ImPlot/plotShaded` implementation

### ISSUE THREAD

**Issue by Tyruiop** [SpaiR/imgui-java#69]
Hi!

While `ImPlot/plotShaded` exists in the library, I cannot find [this specific](https://github.com/epezent/implot/blob/master/implot.h#L527) version of the call, with two `ys` vectors. Is there a way to call it in the library or is it missing?

**Comment by SpaiR** [comment]
The method is missing and should be manually added to the API. Anyone can make a PR with improvements though.
