### ISSUE TITLE
DockNodeBuilder?

### ISSUE THREAD

**Issue by MrManiacc** [SpaiR/imgui-java#7]
Hi any chance we could get support for dock node builder? Right now I have to set the position of child windows to where they should and move them to dock onto the parent/bg window if I want them to be split. Would be nice if we could have the windows split on the start of the application. Regardless thanks again for the awesome bindings and sorry to bother you so much!

**Comment by SpaiR** [comment]
I don't know. It's a part of the internal API, which I didn't plan to port. At least until I won't need some of its functionality for myself. For now I don't need anything of it though.

**Comment by MrManiacc** [comment]
I understand. Any chance you could give a quick overview of how I might implement it? All good if it's to hard to explain.

**Comment by SpaiR** [comment]
As I understand, you're already know how to build libraries, so things go easier.

To create binding itself I use jnigen from libgdx. Its overview and introduction of how to use it could be found here: https://github.com/libgdx/libgdx/wiki/jnigen#how-it-works 

Go through the code inside of `imgui-binding` module. Most of the time everything goes pretty straightforward: https://github.com/SpaiR/imgui-java/blob/master/imgui-binding/src/main/java/imgui/ImGui.java#L260-L262

Sometimes things require more specific approach (especially when you need to transfer an object between native and java layers), but examples could be found as well.

**Comment by MrManiacc** [comment]
Thank you, i'm going to look into this. If I get it working i'll shoot you a PR

**Comment by MrManiacc** [comment]
I can't seem to get it to build on windows. Would really like if you could look into adding that feature if you ever get some free time, I get this is a free project so you're not required to and you only need to add what you need; but I know it would benefit the community greatly, that is kinda a key feature that is directly in correlation with docking, would love to see it pushed. Anyway I understand if you're too busy, but if you ever get a chance it's be greatly appreciated!

**Comment by SpaiR** [comment]
DockBuilder API has been added with https://github.com/SpaiR/imgui-java/releases/tag/v1.78-1.1

Java example of how to create dockspace and docked windows: https://github.com/SpaiR/imgui-java/blob/v1.78-1.1/imgui-lwjgl3/src/test/java/ExampleUi.java#L50-L53
