### ISSUE TITLE
Results of getGlyphRangesChinese*() are cut-off

### ISSUE THREAD

**Issue by MontyHimself** [SpaiR/imgui-java#70]
The glyph range arrays provided by the functions `ImFontAtlas.getGlyphRangesChineseFull()` and `ImFontAtlas.getGlyphRangesChineseSimplifiedCommond()` are cut-off after the first 4 ranges.

For example, with `getGlyphRangesChineseFull()` it is supposed to be this array ([see here](https://github.com/ocornut/imgui/blob/d9b606672ae145457d12dacdc82b82c6ce9ebd79/imgui_draw.cpp#L2830)):
```java
0x0020, 0x00FF, // Basic Latin + Latin Supplement
0x2000, 0x206F, // General Punctuation
0x3000, 0x30FF, // CJK Symbols and Punctuations, Hiragana, Katakana
0x31F0, 0x31FF, // Katakana Phonetic Extensions
0xFF00, 0xFFEF, // Half-width characters
0xFFFD, 0xFFFD, // Invalid
0x4e00, 0x9FAF, // CJK Ideograms
```

The result from the method returns just the first four ranges, though:
```java
0x0020, 0x00FF, // Basic Latin + Latin Supplement
0x2000, 0x206F, // General Punctuation
0x3000, 0x30FF, // CJK Symbols and Punctuations, Hiragana, Katakana
0x31F0, 0x31FF, // Katakana Phonetic Extensions
```

Note that all but one of the missing values are too large for a Java short (e.g. 0xFF00). I don't know what exactly happens during a JNI call, but it looks to me like the data is cut-off because it doesn't fit into the signed short data type. If that is true, one solution would be to use a char instead of a short here, considering it is unsigned and could represent all the relevant glyph ranges necessary (the ImWchar16 used in C++ dear imgui is also an unsigned 16 bit data type).

**Comment by SQwatermark** [comment]
There is no need to use char.
It's better to change jni method `imFontAtlas.getGlyphRangesChineseFull()` to
``` java
    public static short[] getGlyphRangesChineseFull() {
        return new short[]{
                (short) 0x0020, (short) 0x00FF, // Basic Latin + Latin Supplement
                (short) 0x2000, (short) 0x206F, // General Punctuation
                (short) 0x3000, (short) 0x30FF, // CJK Symbols and Punctuations, Hiragana, Katakana
                (short) 0x31F0, (short) 0x31FF, // Katakana Phonetic Extensions
                (short) 0xFF00, (short) 0xFFEF, // Half-width characters
                (short) 0xFFFD, (short) 0xFFFD, // Invalid
                (short) 0x4e00, (short) 0x9FAF, // CJK Ideograms
                (short) 0,
        };
    }
```
copied from https://github.com/ocornut/imgui/blob/d9b606672ae145457d12dacdc82b82c6ce9ebd79/imgui_draw.cpp#L2830
