### ISSUE TITLE
Add ImGuiContext

### ISSUE THREAD

**Issue by EddeDev** [SpaiR/imgui-java#71]

**Comment by SpaiR** [comment]
ImGuiContext is already available https://github.com/SpaiR/imgui-java/blob/master/imgui-binding/src/main/java/imgui/internal/ImGuiContext.java
If you expect it to have more fields/methods - feel free to make a PR with changes. Especially if it's something specific. I'm OK with it's partial implementation if it's goes with general codestyle.
