### ISSUE TITLE
Implement ImGuiFileDialog

### ISSUE THREAD

**Issue by FlorianMichael** [SpaiR/imgui-java#78]
hi,
would it be possible to make an implementation for https://github.com/aiekick/ImGuiFileDialog?

**Comment by SocketByte** [comment]
I'd say you shoud use a native file dialog anyway. ImGuiFileDialog isn't particularly good (saying from experience) and if you don't have a valid reason to use it then I would not recommend it.

You can use [Native File Dialogs](https://github.com/mlabbe/nativefiledialog) instead (LWJGL3 has [bindings ](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/util/nfd/HelloNFD.java)for it)

**Comment by FlorianMichael** [comment]
thanks
