### ISSUE TITLE
ImGuiViewport support for complete window docking?

### ISSUE THREAD

**Issue by PixelRifts** [SpaiR/imgui-java#8]

**Comment by SpaiR** [comment]
As I've described in the readme, API for viewports is unstable. I don't plan to bother myself about that until the official release for sure. 

It also need to be mention, that the API itself is VERY complex. Even in a terms of the original repository. From the binding perspective complexity is doubling or even tripling. I admit the possibility that it will be impossible to implement viewports from Java layer. So don't make any expectations about it.

**Comment by PixelRifts** [comment]
NP. 👍

**Comment by PixelRifts** [comment]
How then should I make my glfw window a complete dockspace? Or can I not?

**Comment by SpaiR** [comment]
See imgui demo https://github.com/ocornut/imgui/blob/docking/imgui_demo.cpp#L5098

My guess is that you should use `dockSpace()` method like here https://github.com/ocornut/imgui/blob/docking/imgui_demo.cpp#L5141

**Comment by PixelRifts** [comment]
What should I pass as the ID to have the whole window be a dockspace??

**Comment by PixelRifts** [comment]
I figured it out. Thanks for the help!

**Comment by PixelRifts** [comment]
I used setNextWindowPos(0, 0) and setNextWindowSize(window_width, window_height) to set the window to occupy the entire glfwwindow. I set its WindowProps so as to prevent resizing the window.
the getID(String) method gave me the id of the imgui window. The parameter was set to be the name of the active window.
getID() returns a long. You have to cast it to an int and pass it in to the dockSpace(int) method. and there you go. :)

```
ImGui.begin("NAME");
long id = ImGui.getID("NAME");
ImGui.dockSpace((int) id);
ImGui.end();
```

Boom! 👍

**Comment by ambye85** [comment]
Thanks, I'll take a look at working that into my code.

**Comment by ambye85** [comment]
> As I've described in the readme, API for viewports is unstable. I don't plan to bother myself about that until the official release for sure.
> 
> It also need to be mention, that the API itself is VERY complex. Even in a terms of the original repository. From the binding perspective complexity is doubling or even tripling. I admit the possibility that it will be impossible to implement viewports from Java layer. So don't make any expectations about that.

@SpaiR This is something I'd like to look into as I've seen the feature in the original C++ and it'd be very useful for my project. But I'm a little unsure where to begin nor where the complexity you describe comes from. Are you able to give some pointers?

**Comment by SpaiR** [comment]
@ambye85 I don't know. Just look at the examples. I can't say anything else because I didn't spend much time on investigating.

**Comment by SpaiR** [comment]
Multi-viewports feature has been added for realease [v1.78-1.0](https://github.com/SpaiR/imgui-java/releases/tag/v1.78-1.0)!

![image](https://user-images.githubusercontent.com/12721311/91667726-4dc4c780-eb0f-11ea-9aec-1658cc17633a.png)
