### ISSUE TITLE
Support for java 9 modules

### ISSUE THREAD

**Issue by tlf30** [SpaiR/imgui-java#82]
Hello,
It would be great to get support for java 9 modules. I am migrating applications to JDK 17 and as part of that migration I am also migrating to java 9 modules. This is now one of the few libraries I am dependent on that is not modular compatible.

**Comment by tlf30** [comment]
#105 is now merged, adding support for Automatic Module Names. Fully implementing Java 9 modules will require additional work that can be done at a future date. For now the main issue has been resolved of using imgui-java in module based applications without the need of performing a reads-all from all unnamed modules.

**Comment by Frooastside** [comment]
Could the package be published to maven, because #105 is merged now. Like v1.86.1 or something like that

**Comment by SpaiR** [comment]
> Could the package be published to maven, because #105 is merged now. Like v1.86.1 or something like that

@Frooastside 1.86.1 is now available.
