### ISSUE TITLE
Version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by gviznyuk** [SpaiR/imgui-java#9]
Greetings,

I'm getting this error with your java bindings on my 18.04 Ubuntu running Java 11:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/imgui-java-bin_gviznyuk/libimgui-java64.so: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by /tmp/imgui-java-bin_gviznyuk/libimgui-java64.so)`

Checked my version: using "lbb --version"

ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by SpaiR** [comment]
Hi!
You need to update your local glibc to the latest version (2.31). Otherwise you can compile binding libraries locally, to be able to use the with your system deps.

**Comment by gviznyuk** [comment]
Will this cross impact anything on my linux if I update libm.so?

**Comment by SpaiR** [comment]
I don't know which apps do you have and which are depend on it. If you don't want to risk, you go with the second solution I've introduces before. But, imho, if you don't have something specific which only works for the earlier version, I don't see any reason not to keep your system up to date.

**Comment by gviznyuk** [comment]
Sorry for the dumb questions, I'm a Java person, so I build glibc and I have libc.so.6 and libc.so, how do I link to them with libimgui-java64.so?

**Comment by SpaiR** [comment]
I'm not sure what are u talking about. If you compiled libimgui-java64.so locally, you've already made a dynamic linking. You can't "link" another version of the library to the compiled binary, that's not how things are work.

**Comment by gviznyuk** [comment]
So I upgrade to 2.31 now, and linked it using the global variable LD_PRELOAD=/opt/glibc-2.31/lib/libc.so

yet I'm still getting the same error.  Does your binary require exactly 2.29?

**Comment by SpaiR** [comment]
Binding requires 2.31. You should probably try ask somewhere else, since it's a general problem when binary can't find a dependency. Nothing specific with imgui-java.

**Comment by SpaiR** [comment]
To summarize: missing of dependencies or versions incompatibility is a user local problem. Common way to handle it is to update system dependencies\install missing libraries. In exceptional cases user can build its own native libraries by himself. Instruction could be found in repo readme.

**Comment by philippludwig** [comment]
Sadly the build fails with:

```
> Could not resolve project :buildSrc.
  Required by:
      project :buildSrc
   > Failed to calculate the value of task ':buildSrc:compileJava' property 'javaCompiler'.
      > Cannot find a Java installation on your machine matching this tasks requirements: {languageVersion=11, vendor=any vendor, implementation=vendor-specific} for LINUX on x86_64.
         > No locally installed toolchains match and toolchain download repositories have not been configured.
```

And the README does not provide instructions on what to do in this case.

It is sad that the limitation to use "ubuntu:latest" in the github actions file makes this library unusable on debian stable. Upgrading glibc is not a good advice, because that basically breaks the whole system.
